### ISSUE TITLE
Homebrew tap gives an error 

### ISSUE THREAD

**Issue by sepsamavi** [openrr/urdf-viz#233]
There seems to be a problem with the homebrew tap. 
```
$ brew install openrr/tap/urdf-viz --verbose
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/formula.rb:306:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:237:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/formulary.rb:494:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:494:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:617:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:734:in `factory'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:89:in `block in create_validator_slow'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:126:in `block in load_formula_or_cask'
/opt/homebrew/Library/Homebrew/api.rb:197:in `with_no_api_env_if_needed'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:118:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:83:in `block in to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `each'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `flat_map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:81:in `to_formulae_and_casks'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/call_validation.rb:157:in `validate_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib/types/private/methods/_methods.rb:270:in `block in _on_method_added'
/opt/homebrew/Library/Homebrew/cmd/install.rb:195:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:86:in `<main>'
```

**Comment by taiki-e** [comment]
openrr/tap does not currently support arm host, but you are attempting to install on arm host, right?

https://github.com/openrr/homebrew-tap/blob/d9a74fc527cc460e712e573857e27abf1b492f99/Formula/urdf-viz.rb

https://github.com/openrr/urdf-viz/pull/147
